project:
  type: website
  output-dir: _site

website:
  title: "Ali Zaidi"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
  page-footer:
    right: "Powered by Quarto"
    left: "Â© 2026 Ali Zaidi"

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    smooth-scroll: true
    highlight-style: github

# This configures the blog listing page
listing:
  contents: posts
  sort: "date desc"
  type: grid           # 'grid' looks more modern than 'default' list
  categories: true
  sort-ui: false
  filter-ui: false
  fields: [image, date, title, reading-time, description]