project:
  type: website
  output-dir: _site

website:
  title: "Ali Zaidi"
  navbar:
    right:
      - text: "About Me"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Resume"
        href: resume.qmd
      - icon: github
        href: https://github.com/azaidi06
      - icon: twitter
        href: https://twitter.com/azaidi06
      - icon: linkedin
        href: https://www.linkedin.com/in/azaidi06
  page-footer:
    right: "Powered by Quarto"
    left: "Â© 2022 Ali Zaidi"

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    code-copy: true
    smooth-scroll: true
    highlight-style: github